-- SUPPRIMER LES TABLES PRECEDENTES
DROP TABLE Participer;
DROP TABLE Personne;
DROP TABLE Jouer;
DROP TABLE Acteur;
DROP TABLE Appartenir;
DROP TABLE Film;
DROP TABLE Categorie;

-- SUPPRESSION DES TABLES SI JAMAIS VOUS VOULEZ REEXECUTER LE SCRIPT
DROP TABLE HISTORIQUE_EVENEMENT;
DROP TABLE DROIT_ACCES;
DROP TABLE ACCES;
DROP TABLE BADGE;
DROP TABLE LIEU;
DROP TABLE PERSONNE;
DROP TABLE PROFIL;

-- 1. Table PROFIL
CREATE TABLE PROFIL 
(
    id_profil       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    libelle_profil  VARCHAR2(50) NOT NULL,
    description     VARCHAR2(255),
    CONSTRAINT      pk_profil PRIMARY KEY (id_profil),
    CONSTRAINT      uq_libelle_profil UNIQUE (libelle_profil)
);

-- 2. Table PERSONNE
CREATE TABLE PERSONNE 
(
    id_personne     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nom             VARCHAR2(100) NOT NULL,
    prenom          VARCHAR2(100) NOT NULL,
    statut          VARCHAR2(20) DEFAULT 'ACTIF' NOT NULL,
    id_profil       NUMBER,
    CONSTRAINT      pk_personne PRIMARY KEY (id_personne),
    CONSTRAINT      fk_personne_id_profil FOREIGN KEY (id_profil) REFERENCES PROFIL(id_profil),
    CONSTRAINT      chk_personne_statut CHECK (statut IN ('ACTIF', 'INACTIF'))
);

-- 3. Table LIEU
CREATE TABLE LIEU 
(
    id_lieu         NUMBER GENERATED BY DEFAULT AS IDENTITY,
    libelle_lieu    VARCHAR2(100) NOT NULL,
    emplacement     VARCHAR2(150) NOT NULL,
    capacite_max    NUMBER(4) DEFAULT 1 NOT NULL,
    statut          VARCHAR2(20) DEFAULT 'OUVERT' NOT NULL,
    CONSTRAINT      pk_lieu PRIMARY KEY (id_lieu),
    CONSTRAINT      chk_lieu_statut CHECK (statut IN ('OUVERT', 'FERME', 'BLOQUE'))
);

-- 4. Table BADGE (Classe d'association unissant PERSONNE et LIEU)
CREATE TABLE BADGE 
(
    num_badge       VARCHAR2(50) NOT NULL,
    date_emission   DATE DEFAULT SYSDATE NOT NULL,
    date_expiration DATE NOT NULL,
    statut          VARCHAR2(20) DEFAULT 'ACTIF' NOT NULL,
    id_personne     NUMBER NOT NULL,
    id_lieu         NUMBER NOT NULL,
    CONSTRAINT      pk_badge PRIMARY KEY (num_badge),
    CONSTRAINT      fk_badge_id_personne FOREIGN KEY (id_personne) REFERENCES PERSONNE(id_personne),
    CONSTRAINT      fk_badge_id_lieu FOREIGN KEY (id_lieu) REFERENCES LIEU(id_lieu) ON DELETE CASCADE,
    CONSTRAINT      chk_badge_statut CHECK (statut IN ('ACTIF', 'SUSPENDU', 'EXPIRE', 'REVOQUE')),
    CONSTRAINT      chk_badge_dates CHECK (date_expiration > date_emission)
);

-- 5. Table ACCES
CREATE TABLE ACCES 
(
    id_acces        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    libelle_acces   VARCHAR2(100) NOT NULL,
    type_acces      VARCHAR2(30) NOT NULL,
    description     VARCHAR2(255),
    id_lieu         NUMBER NOT NULL,
    CONSTRAINT      pk_acces PRIMARY KEY (id_acces),
    CONSTRAINT      fk_acces_id_lieu FOREIGN KEY (id_lieu) REFERENCES LIEU(id_lieu) ON DELETE CASCADE,
    CONSTRAINT      chk_type_acces CHECK (type_acces IN ('PORTE', 'BARRIERE', 'PORTILLON', 'PARKING', 'ASCENSEUR'))
);

-- 6. Table DROIT_ACCES
CREATE TABLE DROIT_ACCES 
(
    id_droit        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_profil       NUMBER NOT NULL,
    id_lieu         NUMBER NOT NULL,
    jour_semaine    VARCHAR2(15) NOT NULL,
    heure_debut     NUMBER(4) NOT NULL,
    heure_fin       NUMBER(4) NOT NULL,
    CONSTRAINT      pk_droit_acces PRIMARY KEY (id_droit),
    CONSTRAINT      fk_droit_id_profil FOREIGN KEY (id_profil) REFERENCES PROFIL(id_profil) ON DELETE CASCADE,
    CONSTRAINT      fk_droit_id_lieu FOREIGN KEY (id_lieu) REFERENCES LIEU(id_lieu) ON DELETE CASCADE,
    CONSTRAINT      chk_jour_semaine CHECK (jour_semaine IN ('LUNDI', 'MARDI', 'MERCREDI', 'JEUDI', 'VENDREDI', 'SAMEDI', 'DIMANCHE', 'TOUS')),
    CONSTRAINT      chk_heure_valide CHECK (heure_fin > heure_debut)
);

-- 7. Table HISTORIQUE_EVENEMENT (Journal Unifié : Accès physique + Audit de Supervision)
CREATE TABLE HISTORIQUE_EVENEMENT 
(
    id_evenement                NUMBER GENERATED BY DEFAULT AS IDENTITY,
    type_evenement              VARCHAR2(30) NOT NULL,
    date_evenement              TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    statut_resultat             VARCHAR2(20) NOT NULL,
    description_justification   VARCHAR2(255) NOT NULL,
    num_badge                   VARCHAR2(50),
    id_acces                    NUMBER,
    id_lieu                     NUMBER,
    id_personne                 NUMBER,
    CONSTRAINT                  pk_historique_evenement PRIMARY KEY (id_evenement),
    CONSTRAINT                  fk_hist_num_badge FOREIGN KEY (num_badge) REFERENCES BADGE(num_badge),
    CONSTRAINT                  fk_hist_id_acces FOREIGN KEY (id_acces) REFERENCES ACCES(id_acces),
    CONSTRAINT                  fk_hist_id_lieu FOREIGN KEY (id_lieu) REFERENCES LIEU(id_lieu),
    CONSTRAINT                  fk_hist_id_personne FOREIGN KEY (id_personne) REFERENCES PERSONNE(id_personne),
    CONSTRAINT                  chk_type_evenement CHECK (type_evenement IN ('ACCES_PHYSIQUE', 'MODIF_BADGE', 'MODIF_LIEU')),
    CONSTRAINT                  chk_statut_resultat CHECK (statut_resultat IN ('ACCORDE', 'REFUSE', 'SUCCES', 'ECHEC'))
);
